[project]
name = "adopt-a-seed-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "pydantic>=2.10.6",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.0",
]
